const FORECAST_ACTIONS = {
  SET_FORECAST_ACTION: 'SET_FORECAST_ACTION',
  ERROR_FETCHING_FORECAST_ACTION: 'ERROR_FETCHING_FORECAST_ACTION',
  LOADING_FORECAST_STATUS_ACTION: 'LOADING_FORECAST_STATUS_ACTION'
};

export default {
  ...FORECAST_ACTIONS
}
