const FORECAST_ACTIONS = {
  SET_FORECAST_ACTION: 'SET_FORECAST_ACTION',
  ERROR_FETCHING_FORECAST_ACTION: 'ERROR_FETCHING_FORECAST_ACTION',
  LOADING_FORECAST_STATUS_ACTION: 'LOADING_FORECAST_STATUS_ACTION'
};

const PRESSURE_ACTIONS = {
  SET_PRESSURE_AVERAGE_ACTION: 'SET_PRESSURE_AVERAGE_ACTION',
  ERROR_FETCHING_PRESSURE_ACTION: 'ERROR_FETCHING_PRESSURE_ACTION',
};

export default {
  ...FORECAST_ACTIONS,
  ...PRESSURE_ACTIONS
}
